#pragma once
#include "cinder/CinderResources.h"

#define RES_CUBE1_ID		CINDER_RESOURCE( ../resources/, cubePosX.jpg,		138, IMAGE )
#define RES_CUBE2_ID		CINDER_RESOURCE( ../resources/, cubePosY.jpg,		139, IMAGE )
#define RES_CUBE3_ID		CINDER_RESOURCE( ../resources/, cubePosZ.jpg,		140, IMAGE )
#define RES_CUBE4_ID		CINDER_RESOURCE( ../resources/, cubeNegX.jpg,		141, IMAGE )
#define RES_CUBE5_ID		CINDER_RESOURCE( ../resources/, cubeNegY.jpg,		142, IMAGE )
#define RES_CUBE6_ID		CINDER_RESOURCE( ../resources/, cubeNegZ.jpg,		143, IMAGE )
#define ICON_TERRAIN_ID		CINDER_RESOURCE( ../resources/, iconTerrain.png,	144, IMAGE )
#define GLOW_ID				CINDER_RESOURCE( ../resources/, glow.png,			145, IMAGE )
#define ROOM_VERT_ID		CINDER_RESOURCE( ../resources/, room.vert,			146, GLSL )
#define ROOM_FRAG_ID		CINDER_RESOURCE( ../resources/, room.frag,			147, GLSL )
#define PASS_THRU_VERT_ID	CINDER_RESOURCE( ../resources/, passThru.vert,		148, GLSL )
#define RD_FRAG_ID			CINDER_RESOURCE( ../resources/, rd.frag,			149, GLSL )
#define HEIGHTS_FRAG_ID		CINDER_RESOURCE( ../resources/, heights.frag,		150, GLSL )
#define NORMALS_FRAG_ID		CINDER_RESOURCE( ../resources/, normals.frag,		151, GLSL )
#define TERRAIN_VERT_ID		CINDER_RESOURCE( ../resources/, terrain.vert,		152, GLSL )
#define TERRAIN_FRAG_ID		CINDER_RESOURCE( ../resources/, terrain.frag,		153, GLSL )
#define SPHERE_VERT_ID		CINDER_RESOURCE( ../resources/, sphere.vert,		154, GLSL )
#define SPHERE_FRAG_ID		CINDER_RESOURCE( ../resources/, sphere.frag,		155, GLSL )
#define WALL_TEX_ID			CINDER_RESOURCE( ../resources/, roomWall1.png,		156, IMAGE )
#define CEILING_TEX_ID		CINDER_RESOURCE( ../resources/, roomCeiling.png,	157, IMAGE )
#define FLOOR_TEX_ID		CINDER_RESOURCE( ../resources/, roomFloor.png,		158, IMAGE )
#define BLANK_TEX_ID		CINDER_RESOURCE( ../resources/, roomBlank.png,		159, IMAGE )
#define GRADIENT_TEX_ID		CINDER_RESOURCE( ../resources/, gradient.png,		160, IMAGE )
#define SAND_NORMAL_TEX_ID	CINDER_RESOURCE( ../resources/, sandNormal.png,		161, IMAGE )
#define BACK_WALL_TEX_ID	CINDER_RESOURCE( ../resources/, roomWall0.png,		162, IMAGE )
